version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: exam-munnodi-redis
    restart: unless-stopped
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD:-}
    networks:
      - exam-network

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: exam-munnodi-redis-commander
    restart: unless-stopped
    ports:
      - '8081:8081'
    environment:
      - REDIS_HOSTS=local:redis:6379:0:${REDIS_PASSWORD:-}
    networks:
      - exam-network
    depends_on:
      - redis

volumes:
  redis_data:

networks:
  exam-network:
    driver: bridge
